# rewrite
redirectMaintenance: false

# Basic Authentication
protectedDefaultPaths: true
serverAuthorization: true
protectedAuthName: "Development Area"
htPasswordClear: changeme123
htPasswordDir: /var/www/dev/public/
htPasswordUser: devuser
allowedPaths:
  - favicon/manifest.json
  - favicon/browserconfig.xml
allowedUserBots:
  - "GoogleBot"
  - "BingBot"
  - "DuckDuckBot"
